server:
  port: 5020
spring:
  datasource:
    url: jdbc:mysql://120.25.218.185:3306/spider?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Pm,189889386
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spider_project