server:
  port: 5020
spring:
  datasource:
    url: jdbc:mysql://120.25.218.185:3306/spider?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Pm,189889386
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spider_project

# rocketMQ配置
rocketmq:
  name-server: 120.25.218.185:9876
  producer:
    group: pengmin
    src:
      group: pengmin
      topic: MES_ERC_SRC_STATUS
  consumer:
    group: pengmin
    topic: MES_ERC_SRC_STATUS
    src:
      group: pengmin
      topic: MES_ERC_SRC_STATUS

debug: true