server:
  port: 5018
spring:
  datasource:
    url: jdbc:mysql://121.196.101.202:3306/spider_vm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spider_project